/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui_Kalkulator;

import java.util.ArrayList;
/**
 *
 * @author MSI
 */
public class FrameKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form FrameKalkulator
     */
    private boolean charAwal = true; //Nunjukin kalo ada angka(1-9) dah masuk, dan juga (,), biar angka 0 enak
    private boolean adaKoma = false; //Nunjukin di suatu angka, hanya bisa 1 koma
    private final char[] allOp = {'+','-','x','÷'};
            
    public FrameKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKalkulator = new javax.swing.JPanel();
        textFieldAfterKalk = new javax.swing.JTextField();
        textFieldKalkulator = new javax.swing.JTextField();
        acButton = new javax.swing.JButton();
        plusMinusButton = new javax.swing.JButton();
        percentButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        timeButton = new javax.swing.JButton();
        minButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        komaButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(364, 537));

        panelKalkulator.setBackground(new java.awt.Color(204, 204, 204));
        panelKalkulator.setPreferredSize(new java.awt.Dimension(350, 500));
        panelKalkulator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldAfterKalk.setEditable(false);
        textFieldAfterKalk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldAfterKalk.setForeground(new java.awt.Color(153, 153, 153));
        textFieldAfterKalk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldAfterKalk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textFieldAfterKalk.setFocusable(false);
        textFieldAfterKalk.setPreferredSize(new java.awt.Dimension(338, 22));
        panelKalkulator.add(textFieldAfterKalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        textFieldKalkulator.setEditable(false);
        textFieldKalkulator.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        textFieldKalkulator.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldKalkulator.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textFieldKalkulator.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldKalkulator.setPreferredSize(new java.awt.Dimension(338, 80));
        panelKalkulator.add(textFieldKalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        acButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        acButton.setText("AC");
        acButton.setPreferredSize(new java.awt.Dimension(80, 70));
        acButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(acButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        plusMinusButton.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        plusMinusButton.setText("+/-");
        plusMinusButton.setPreferredSize(new java.awt.Dimension(80, 70));
        plusMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(plusMinusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 120, -1, -1));

        percentButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        percentButton.setText("%");
        percentButton.setPreferredSize(new java.awt.Dimension(80, 70));
        percentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(percentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 120, -1, -1));

        divideButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        divideButton.setText("÷");
        divideButton.setPreferredSize(new java.awt.Dimension(80, 70));
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(divideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 120, -1, -1));

        timeButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        timeButton.setText("x");
        timeButton.setPreferredSize(new java.awt.Dimension(80, 70));
        timeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(timeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 196, -1, -1));

        minButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        minButton.setText("-");
        minButton.setPreferredSize(new java.awt.Dimension(80, 70));
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(minButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 272, -1, -1));

        plusButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        plusButton.setText("+");
        plusButton.setPreferredSize(new java.awt.Dimension(80, 70));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 348, -1, -1));

        enterButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        enterButton.setText("=");
        enterButton.setPreferredSize(new java.awt.Dimension(80, 70));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 424, -1, -1));

        komaButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        komaButton.setText(",");
        komaButton.setPreferredSize(new java.awt.Dimension(80, 70));
        komaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(komaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 424, -1, -1));

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        deleteButton.setText("<-");
        deleteButton.setPreferredSize(new java.awt.Dimension(80, 70));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 424, -1, -1));

        zeroButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setPreferredSize(new java.awt.Dimension(80, 70));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(zeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 424, -1, -1));

        oneButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        oneButton.setText("1");
        oneButton.setPreferredSize(new java.awt.Dimension(80, 70));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(oneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, -1, -1));

        twoButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        twoButton.setText("2");
        twoButton.setPreferredSize(new java.awt.Dimension(80, 70));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(twoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 348, -1, -1));

        threeButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        threeButton.setText("3");
        threeButton.setPreferredSize(new java.awt.Dimension(80, 70));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(threeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 348, -1, -1));

        fourButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fourButton.setText("4");
        fourButton.setPreferredSize(new java.awt.Dimension(80, 70));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(fourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, -1, -1));

        fiveButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setPreferredSize(new java.awt.Dimension(80, 70));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(fiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 272, -1, -1));

        sixButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sixButton.setText("6");
        sixButton.setPreferredSize(new java.awt.Dimension(80, 70));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(sixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 272, -1, -1));

        sevenButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setPreferredSize(new java.awt.Dimension(80, 70));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(sevenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, -1, -1));

        eightButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        eightButton.setText("8");
        eightButton.setPreferredSize(new java.awt.Dimension(80, 70));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(eightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 196, -1, -1));

        nineButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nineButton.setText("9");
        nineButton.setPreferredSize(new java.awt.Dimension(80, 70));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });
        panelKalkulator.add(nineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 196, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItem(String addTextF)
    {
        String textF = textFieldKalkulator.getText() + addTextF;
        textFieldKalkulator.setText(textF);
    }
    
    private boolean cekOp(char usedOp)
    {
        for (char Op : allOp)
        {
            if (usedOp == Op)
            {
                return true;
            }
        }
        return false;
    }
    
    private void gantiOp(String usedOp)
    {
        deleteOneNumber();
        addItem(usedOp);
    }
    
    private void deleteOneNumber()
    {
        String text = textFieldKalkulator.getText();
        StringBuilder sb = new StringBuilder(text);
        sb.deleteCharAt(text.length() - 1);
        textFieldKalkulator.setText(sb.toString());
    }
    
    private void resetVar()
    {
        charAwal = true;
        adaKoma = false;
    }
    
    private String Hitung(String text)
    {
        ArrayList<String> listString = new ArrayList<>();
        char charIni;
        char charDepan;
        String arrayItem = new String();
        
        //Pemisah String jadi Array
        for (int i = 0; i < (text.length()); i++)
        {
            charIni = text.charAt(i);
            charDepan = text.charAt(i+1);
            if (charIni == 'E' && charDepan == '-') //E-
            {
                arrayItem += "E-";
                i++;
            }
            else if ((charIni == 'x' && charDepan == '-') || (charIni == '÷' && charDepan == '-')) //x- ÷-
            {
                listString.add(arrayItem);
                arrayItem = "";
                arrayItem += "" + charIni;
                arrayItem += "" + charDepan;
                listString.add(arrayItem);
                arrayItem = "";
                i++;
            }
            else if (charIni == 'x' || charIni == '+' || charIni == '-' || charIni == '÷' ) //x + - ÷
            {
                listString.add(arrayItem);
                arrayItem = "";
                listString.add("" + charIni);
            }
            else if (charIni == '%' ) //khusus persen
            {
            	listString.add(arrayItem);
            	arrayItem = "" + charIni;
            }
            else if (charIni == '_') // buat nge end loop (dari _)
            {
            	listString.add(arrayItem);
            	i++;
            }
            else // angka biasa
            {
                if (charIni == ',')
                {
                    arrayItem += "" + '.';
                }
                else
                {
                    arrayItem += "" + charIni;
                }
            }
        }
        //Pemisah selesai
            
        String stringIni;
        double HasilDouble;
        
        //Hitung Persen
        for(int i = 0; i < listString.size(); i++)
        {
            HasilDouble = 0.0;
            stringIni = listString.get(i);
            if (stringIni.equals("%"))
            {
                HasilDouble = Double.parseDouble(listString.get(i-1)) / 100;
                listString.remove(i-1);
                listString.remove(i-1);
                listString.add(i-1, String.valueOf(HasilDouble));
                i -= 1;
            }
        }
        //Persen Selesai
        
        //Hitung PerkaliandanPembagian
        for (int i = 0; i < listString.size(); i++)
        {
            HasilDouble = 0.0;
            stringIni = listString.get(i);
            if (stringIni.equals("x") || stringIni.equals("÷") || stringIni.equals("x-") || stringIni.equals("÷-"))
            {
                if (stringIni.equals("÷"))
                {
                    HasilDouble = Double.parseDouble(listString.get(i-1)) / Double.parseDouble(listString.get(i+1));
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.add(i-1, String.valueOf(HasilDouble)); // mengubah hasil dari double ke string;
                    i -= 1;
                }
                else if (stringIni.equals("x"))
                {
                    HasilDouble = Double.parseDouble(listString.get(i-1)) * Double.parseDouble(listString.get(i+1));
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.add(i-1, String.valueOf(HasilDouble)); // mengubah hasil dari double ke string;
                    i -= 1;
                }
                else if (stringIni.equals("x-"))
                {
                    HasilDouble = Double.parseDouble(listString.get(i-1)) * -1 * Double.parseDouble(listString.get(i+1));
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.add(i-1, String.valueOf(HasilDouble));
                    i-=1;
                }
                else if (stringIni.equals("÷-"))
                {
                    HasilDouble = Double.parseDouble(listString.get(i-1)) * -1 / Double.parseDouble(listString.get(i+1));
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.remove(i-1);
                    listString.add(i-1, String.valueOf(HasilDouble));
                    i-=1;
                }
            }
        }
        //Perkalian dan Pembagian Selesai
        
        //Hitung Penjumlahan dan Pengurangan
        for ( int i = 0; i < listString.size(); i++)
        {
            HasilDouble = 0.0;
            stringIni = listString.get(i);
            if (stringIni.equals("+"))
            {
                HasilDouble = Double.parseDouble(listString.get(i-1)) + Double.parseDouble(listString.get(i+1));
                listString.remove(i-1);
                listString.remove(i-1);
                listString.remove(i-1);
                listString.add(i-1, String.valueOf(HasilDouble));
                i -= 1;
            }
            else if (stringIni.equals("-"))
            {
                HasilDouble = Double.parseDouble(listString.get(i-1)) - Double.parseDouble(listString.get(i+1));
                listString.remove(i-1);
                listString.remove(i-1);
                listString.remove(i-1);
                listString.add(i-1, String.valueOf(HasilDouble));
                i -= 1;
            }
        }
        //Penjumlahan dan Penguarang Selesai
        
        
        HasilDouble = (double) Double.parseDouble(listString.get(0));
        double EPSILON = 1e-15;
        
        //Menghilangkan angka 0 didepan angka, karena tidak terdeteksi oleh Operator yang ada. (0 + textfield...)
        listString.add("" + HasilDouble);
        listString.remove(0);
        //Menghilangkan angka 0 selesai
        
        //Apakah Hasil double atau integer
        if (Math.abs(HasilDouble - Math.round(HasilDouble)) < EPSILON) //Penjelasan ada di Package Belajar test2.java
        {
            charAwal = false; adaKoma = false;
            int HasilInteger = (int) HasilDouble;
            return "" + HasilInteger;
            //Mengirim integer
        }
        else
        {
            charAwal = false; adaKoma = true;
            //Mengubah . menjadi ,
            for ( int i = 0; i < listString.get(0).length(); i++)
            {
                if (listString.get(0).charAt(i) == '.')
                {
                    listString.add(listString.get(0).replace('.', ','));
                    listString.remove(0);
                }
            }
            //. menjadi , selesai

            return "" + listString.get(0);
            //Mengirim String double yang . udah diubah jadi ,
        }
    }
    
    private void acButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acButtonActionPerformed
        // TODO add your handling code here:
        textFieldKalkulator.setText("");
        resetVar();
    }//GEN-LAST:event_acButtonActionPerformed

    private void plusMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusMinusButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder text = new StringBuilder(textFieldKalkulator.getText());
        if (text.length() == 0)
        {}
        else if (text.charAt(0) != '-')
        {
            textFieldKalkulator.setText("-" + text);
        }
        else if(text.charAt(0) == '-')
        {
            text.deleteCharAt(0);
            textFieldKalkulator.setText(text.toString());
        }
    }//GEN-LAST:event_plusMinusButtonActionPerformed

    private void percentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {}
        else if (text.charAt(text.length() - 1) == '0' || text.charAt(text.length() - 1) == '%') //Karena 0 char awal (biar kalo mau masukin angka(1-9) jadi keganti), maka hrus buat ini
        {
            addItem("%");
            resetVar();
        }
        else if (charAwal == false && text.charAt(text.length() - 1) != ',') //Udah ada angka (1-9) dan bukan akhiran koma, baru bisa dimasukin
        {
            addItem("%");
            resetVar();
        }
    }//GEN-LAST:event_percentButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {}
        else if (text.length() == 1 && text.charAt(text.length() - 1) == '-')
        {}
        else if (text.charAt(text.length() - 1) == '0' || text.charAt(text.length() - 1) == '%')
        {
            addItem("÷");
            resetVar();
        }
        else if (charAwal == false && text.charAt(text.length() - 1) != ',')
        {
            addItem("÷");
            resetVar();
        }
        else if((text.charAt(text.length() - 2) == 'x' || text.charAt(text.length() - 2) == '÷'))
        {
            deleteOneNumber(); //auto resetVar();
            gantiOp("÷");
        }
        else if(charAwal == true && cekOp(text.charAt(text.length() - 1)) == true)
        {
            gantiOp("÷"); //auto resetVar();
        }
    }//GEN-LAST:event_divideButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {}
        else if (text.length() == 1 && text.charAt(text.length() - 1) == '-')
        {}
        else if (text.charAt(text.length() - 1) == '0' || text.charAt(text.length() - 1) == '%')
        {
            addItem("x");
            resetVar();
        }
        else if (charAwal == false && text.charAt(text.length() - 1) != ',')
        {
            addItem("x");
            resetVar();
        }
        else if((text.charAt(text.length() - 2) == 'x' || text.charAt(text.length() - 2) == '÷'))
        {
            deleteOneNumber(); //auto resetVar();
            gantiOp("x");
        }
        else if(charAwal == true && cekOp(text.charAt(text.length() - 1)) == true)
        {
            gantiOp("x"); //auto resetVar();
        }
    }//GEN-LAST:event_timeButtonActionPerformed

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("-");
        }
        else if (text.charAt(text.length() - 1) == '0' || text.charAt(text.length() - 1) == '%' || 
                 text.charAt(text.length() - 1) == 'x'|| text.charAt(text.length() - 1) == '÷')
        {
            addItem("-");
            resetVar();
        }
        else if (charAwal == false && text.charAt(text.length() - 1) != ',')
        {
            addItem("-");
            resetVar();
        }
        else if (charAwal == true && text.charAt(text.length() - 1) == '+')
        {
            gantiOp("-");
        }
    }//GEN-LAST:event_minButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {}
        else if ((text.length() == 1 && text.charAt(text.length() - 1) == '-'))
        {}
        else if (text.charAt(text.length() - 1) == '0' || text.charAt(text.length() - 1) == '%')
        {
            addItem("+");
            resetVar();
        }
        else if (charAwal == false && text.charAt(text.length() - 1) != ',')
        {
            addItem("+");
            resetVar();
        }
        else if((text.charAt(text.length() - 2) == 'x' || text.charAt(text.length() - 2) == '÷'))
        {
            deleteOneNumber(); //auto resetVar();
        }
        else if(charAwal == true && (cekOp(text.charAt(text.length() - 1)) == true))
        {
            gantiOp("+"); //auto resetVar();
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        String text = "0" + textFieldKalkulator.getText() + "__";
        if (text.charAt(text.length()-3) == 'x' || text.charAt(text.length()-3) == '÷' || 
                text.charAt(text.length()-3) == '+' || text.charAt(text.length()-3) == '-' || 
                text.charAt(text.length()-3) == ',') // (-3) Soalnya ada tambahan "0"  dan "__", kalo ga ada ya -1 kayak biasa.
        {}
        else
        {
            String hasil = Hitung(text);
            textFieldAfterKalk.setText(textFieldKalkulator.getText());
            textFieldKalkulator.setText(hasil);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void komaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (charAwal == true && adaKoma == false) //Bilangan baru
        {
            if (text.length() == 0) //Buat diawal
            {
                addItem("0,");
                adaKoma = true;
            }
            else if (text.charAt(text.length() - 1) == '0')
            {
                addItem(",");
                adaKoma = true;
            }
            else if (text.charAt(text.length() - 1) == '%')
            {}
            else //Buat setelah operator
            {
                addItem("0,");
                adaKoma = true;
            }
        }
        else if (charAwal == false && adaKoma == false)//Sudah ada bilangan sebelumnya
        {
            addItem(",");
            adaKoma = true;
        }
    }//GEN-LAST:event_komaButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        
        if(text.length() == 0)
        {}
        if (text.length() == 1) //hapus 1 number, biar length() - 2 ga erorr dibawah itu
        {
            deleteOneNumber();
            resetVar();
        }
        else if (text.charAt(text.length()-1) == ',') //Kalo Hapus Koma
        {
            deleteOneNumber();
            adaKoma = false;
        }
        else if (text.charAt(text.length()-2) == 'x' || text.charAt(text.length()-2) == '÷' || 
                text.charAt(text.length()-2) == '+' || text.charAt(text.length()-2) == '-') // Kalau delete sebelah kirinya ada op, jadi Bilangan baru
        {
            deleteOneNumber();
            resetVar();
        }
        else //Kalau delete operator dan angka?
        {
            deleteOneNumber();
            charAwal = false;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText(); //Selama 0 dan True ga akan bisa nambah 0
        if (text.length() == 0)
        {
            addItem("0");
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (text.charAt(text.length() - 1) == '0')
        {
            if(charAwal == false)
            {
                addItem("0");
            }
        }
        else if (adaKoma == true)
        {
            addItem("0");
            charAwal = false;
        }
        else
        {
            addItem("0");
        }
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("1");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("1");
            charAwal = false;
        }
        else
        {
            addItem("1");
            charAwal = false;
        }
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("2");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("2");
            charAwal = false;
        }
        else
        {
            addItem("2");
            charAwal = false;
        }
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("3");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("3");
            charAwal = false;
        }
        else
        {
            addItem("3");
            charAwal = false;
        }
    }//GEN-LAST:event_threeButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("4");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("4");
            charAwal = false;
        }
        else
        {
            addItem("4");
            charAwal = false;
        }
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("5");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("5");
            charAwal = false;
        }
        else
        {
            addItem("5");
            charAwal = false;
        }
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("6");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("6");
            charAwal = false;
        }
        else
        {
            addItem("6");
            charAwal = false;
        }
    }//GEN-LAST:event_sixButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("7");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("7");
            charAwal = false;
        }
        else
        {
            addItem("7");
            charAwal = false;
        }
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("8");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("8");
            charAwal = false;
        }
        else
        {
            addItem("8");
            charAwal = false;
        }
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        // TODO add your handling code here:
        String text = textFieldKalkulator.getText();
        if (text.length() == 0)
        {
            addItem("9");
            charAwal = false;
        }
        else if (text.charAt(text.length() - 1) == '%')
        {}
        else if (charAwal == true && text.charAt(text.length()-1) == '0')
        {
            deleteOneNumber();
            addItem("9");
            charAwal = false;
        }
        else
        {
            addItem("9");
            charAwal = false;
        }
    }//GEN-LAST:event_nineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton komaButton;
    private javax.swing.JButton minButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JPanel panelKalkulator;
    private javax.swing.JButton percentButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton plusMinusButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JTextField textFieldAfterKalk;
    private javax.swing.JTextField textFieldKalkulator;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton timeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
